language: node_js

node_js: lts/*

env:
  global:
    - secure: "u9AaR7Cq+MHqabmf/1Y43kJLciEL4+NX2N9BAFKtWy7ylA3QBbMyV3GGOP4+/aI0xXBh6k7BxOj85Q0CtNQqsevkNkyZjsHUBHbF/htxBY8+RYR1WhWcKE+OWqH5tHzqWFNVDF58QF90kBDoCBP0QJ1/GfK62CQXTAw+Aqthr/omFADYMfwr5jCqeIAX3g5pHJEqQnBHdZkU6jMPd2aUdTr9SLxnAR5QylzF+hdSwOAb1MvyXdFxfAbBgsr0915LWEpvDh/gi9dxCb+jHyK3wlwbk32RQzd8uiE+gTdqyTiCIO8vFgckxd3EmawCrFHfyGLTJKrQPHUvNqMJpHhKYm2atKeJH5X4N4lQmfVqt3/8KhR4LTy9M8hTRTtLNXJKfmyEI9/GWe0szPlhyNljYdmjTXGIv4bxPOU98Uk4CSr4LoWhpAUe9MkVhNOYbb2lDie7WUqtPR3I5nxldCs3hCXD5+iurnY7RNohjbgfM/7yyuKNAtlTcFf+5mkO0b0HZdB4FpZpKw9MN7euvaydvzIFD9EcNSZQVJTT95HguCOulv5KAZwkmICsrvy4L/mNOhNE9BSimsVHejcflmNN0b42+2EsK0as0qK2GYQ4sJFrqv6D5/+eQXrozMDILJoUl8m4JFhJepteklfzYzM7wxl/YIcn1cgmqxSYg3QPIaM="
    - secure: "n/XzuLG0WxZmZTLryFRrJtw59/pWIbteewAHH1SJAzucC6+LL9rMVmhZu2zmueGCLTrkdiVXt8XVXewWVck0xozJtScniqx+fPygKxNDIr5gyMAJjVzk+Kj3Ybg0kRtCyoFZtb7pSPI+x7nYzIZtnyGMzg1TV7dtFjSylZVZHFspNNQgLkhT35ZEgvZcd0rpwFL+8j13u4ojA4CYC9sjs7VETTVet1FxCMmssdsq6Nr+yG7RdhgPLB4eA7DziQP8vfvzbbAgpJkUB81CNS0DvIgRdmbFcIGNuv4dbZHn2IKmnOlGe/18/qSFrWiyE2pySApHDZgESY3AQcBqWipWgGMm7GxqvCjKIf1mwc1HSfYo7b+ePFzfCiWbRH5FBP3wYU6c0LV1Jpy1iPcKGcYLBNC8Pd5MCQrdsnc54X94E0I0OVLDSEWitekeSfjZSKj+IufTIVLr0meTLPtBkj/O+bpUfEMrjXMRvkyumYwm/HDMX0FfWB+WpaG4XGexQp0j2svm/fo4CkV3j9wxYDMMbS2YpyMES/GWynGlbEvO6qCur6RtcfPcbkJeZf8nkSyEjwaufcV71X6x44PcRGauhWjPiJ/hKSvVkEwX1Xi7aLKBkHBvSh6r3CEMeWqaanNKsWNhqFxtQchALMUM+CegVussgR2Z7lopPmmzCzD+TWQ="

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE knecht;'

script:
  - node src/main.js --debug $BOTTOKEN

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git clone https://zekroTJA:$GITHUB_API_KEY@github.com/zekroTJA/knechtV3.wiki.git
    mv cmdlist.md knechtV3.wiki/Commands.md
    cd knechtV3.wiki
    git add .
    git -c user.name="travis" -c user.email="travis" commit -m "automatically updated commands list"
    git push
  fi
